// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/poll": {
            "post": {
                "description": "Создает новый опрос с указанными параметрами",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polls"
                ],
                "summary": "Создать новый опрос",
                "parameters": [
                    {
                        "description": "Данные для создания опроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/poll.CreatePollRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/poll.CreatePollResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/poll/complete": {
            "patch": {
                "description": "Позволяет создателю завершить опрос до установленного срока окончания",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polls"
                ],
                "summary": "Завершить опрос досрочно",
                "parameters": [
                    {
                        "description": "Данные для досрочного завершения опроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/poll.CompletePollRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Опрос успешно завершен",
                        "schema": {
                            "$ref": "#/definitions/poll.CompletePollResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Только создатель может выполнить это действие",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Опрос не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/poll/delete": {
            "delete": {
                "description": "Удаляет существующий опрос (доступно только создателю опроса)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polls"
                ],
                "summary": "Удалить опрос",
                "parameters": [
                    {
                        "description": "Данные для удаления опроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/poll.DeletePollRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Опрос успешно удален",
                        "schema": {
                            "$ref": "#/definitions/poll.DeletePollResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Только создатель может выполнить это действие",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Опрос не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/results": {
            "get": {
                "description": "Возвращает текущие результаты голосования по указанному опросу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polls"
                ],
                "summary": "Получить результаты опроса",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 123,
                        "description": "ID опроса",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный запрос",
                        "schema": {
                            "$ref": "#/definitions/poll.ResultsPollResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Опрос не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vote": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Записывает голос пользователя в указанном опросе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Votes"
                ],
                "summary": "Создать голос",
                "parameters": [
                    {
                        "description": "Данные голоса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vote.CreateVoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Голос успешно учтен",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Вы уже голосовали в этом опросе",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Опрос не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "poll.CompletePollRequest": {
            "type": "object",
            "properties": {
                "poll_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "poll.CompletePollResponse": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "poll_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "poll.CreatePollRequest": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "question": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "poll.CreatePollResponse": {
            "type": "object",
            "properties": {
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "poll_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "poll.DeletePollRequest": {
            "type": "object",
            "properties": {
                "poll_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "poll.DeletePollResponse": {
            "type": "object",
            "properties": {
                "deleted_by": {
                    "type": "string"
                },
                "poll_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "poll.ResultsPollResponse": {
            "type": "object",
            "properties": {
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "question": {
                    "type": "string"
                },
                "votes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        },
        "vote.CreateVoteRequest": {
            "type": "object",
            "properties": {
                "option": {
                    "type": "string"
                },
                "poll_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Poll API",
	Description:      "API системы опросов и голосований",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
